Repository googleapis/python-containeranalysis, pull requests merged in 2020-12, with the labels that each got.

#63 chore: updating CODEOWNERS to new CICD DPE team
  .github/CODEOWNERS
Labels: api: containeranalysis, cla: yes

#60 chore: require samples checks
  .github/sync-repo-settings.yaml
Labels: api: containeranalysis, cla: yes, samples

#58 chore: Updating docs mapping and synthtool metadata
  docs/conf.py
  synth.metadata
Labels: api: containeranalysis, cla: yes, context: partial

#66 chore: add pre-commit hook
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  noxfile.py
  samples/snippets/noxfile.py
  synth.metadata
  synth.py
Labels: api: containeranalysis, cla: yes, context: partial

#68 fix: remove client recv msg limit and add enums to `types/__init__.py`
  google/cloud/devtools/containeranalysis_v1/services/container_analysis/transports/__init__.py
  google/cloud/devtools/containeranalysis_v1/services/container_analysis/transports/grpc.py
  google/cloud/devtools/containeranalysis_v1/services/container_analysis/transports/grpc_asyncio.py
  google/cloud/devtools/containeranalysis_v1/types/__init__.py
  synth.metadata
  tests/unit/gapic/containeranalysis_v1/test_container_analysis.py
Labels: api: containeranalysis, cla: yes, context: full

#70 chore(deps): update precommit hook pre-commit/pre-commit-hooks to v3.4.0
  .pre-commit-config.yaml
  synth.metadata
Labels: api: containeranalysis, cla: yes, context: full

#72 chore: exclude `.nox` from linting; document supported python versions
  .flake8
  CONTRIBUTING.rst
  synth.metadata
Labels: api: containeranalysis, cla: yes, context: full
