Repository googleapis/python-containeranalysis, pull requests merged in 2021-05, with the labels that each got.

#124 [CHANGE ME] Re-generated to pick up changes from self.
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  noxfile.py
  synth.metadata
Labels: api: containeranalysis, cla: yes, context: none

#125 chore: add library type to .repo-metadata.json
  .repo-metadata.json
Labels: api: containeranalysis, cla: yes

#132 chore: add cicd (devplat) team to codeowners
  .repo-metadata.json
Labels: api: containeranalysis, cla: yes

#135 fix(deps): add packaging requirement
  setup.py
  testing/constraints-3.6.txt
Labels: api: containeranalysis, automerge, cla: yes
