Repository googleapis/python-containeranalysis, pull requests merged in 2021-04, with the labels that each got.

#103 fix: require google-api-core >= 1.22.2
  .pre-commit-config.yaml
  UPGRADING.md
  noxfile.py
  setup.py
  synth.metadata
  testing/constraints-3.6.txt
Labels: api: containeranalysis, cla: yes, context: full

#106 test: fix flaky test
  samples/snippets/samples_test.py
Labels: api: containeranalysis, cla: yes

#110 chore: start tracking obsolete files
  synth.metadata
Labels: api: containeranalysis, cla: yes, context: full

#113 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: containeranalysis, automerge, cla: yes, context: full

#114 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  samples/snippets/noxfile.py
  synth.metadata
Labels: api: containeranalysis, cla: yes, context: full, samples

#117 chore: Re-generated to pick up changes from synthtool
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: containeranalysis, cla: yes, context: full

#118 chore: prevent normalization of semver versioning
  setup.py
Labels: api: containeranalysis, cla: yes

#120 chore(revert): revert preventing normalization
  setup.py
Labels: api: containeranalysis, cla: yes
